const reglas= [
{antecedents:["Limpieza dental","Spa","Corte de pelo","Baño para perros"],consequents:["Tratamiento de sarna"]},
{antecedents:["Spa","Corte de pelo","Corte de uñas","Baño para perros"],consequents:["Tratamiento de sarna"]},
{antecedents:["Limpieza dental","Corte de pelo","Corte de uñas","Baño para perros"],consequents:["Tratamiento de sarna"]},
{antecedents:["Limpieza dental","Spa","Tratamiento de sarna","Corte de uñas"],consequents:["Corte de pelo"]},
{antecedents:["Baño para perros","Tratamiento de sarna","Corte de uñas","Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Limpieza dental","Spa","Tratamiento de sarna"],consequents:["Corte de pelo"]},
{antecedents:["Limpieza dental","Spa","Tratamiento de sarna","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Tratamiento de sarna","Baño para perros","Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Limpieza dental","Tratamiento de sarna","Corte de uñas"],consequents:["Corte de pelo"]},
{antecedents:["Tratamiento de sarna","Corte de uñas","Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Corte de pelo","Corte de uñas","Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Limpieza dental","Tratamiento de sarna"],consequents:["Corte de pelo"]},
{antecedents:["Limpieza dental","Tratamiento de sarna","Corte de uñas","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Limpieza dental","Tratamiento de sarna","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Limpieza dental","Spa","Corte de uñas"],consequents:["Corte de pelo"]},
{antecedents:["Limpieza dental","Tratamiento de sarna","Corte de uñas"],consequents:["Baño para perros"]},
{antecedents:["Tratamiento de sarna","Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Tratamiento de sarna"],consequents:["Corte de pelo"]},
{antecedents:["Corte de pelo","Corte de uñas"],consequents:["Limpieza dental"]},
{antecedents:["Tratamiento de sarna","Corte de uñas"],consequents:["Baño para perros"]},
{antecedents:["Limpieza dental","Tratamiento de sarna","Corte de uñas","Corte de pelo"]},
{antecedents:["Tratamiento de sarna"],consequents:["Corte de pelo"]},
{antecedents:["Tratamiento de sarna","Baño para perros"],consequents:["Limpieza dental"],},
{antecedents:["Spa","Tratamiento de sarna","Corte de uñas"],consequents:["Corte de pelo"]},
{antecedents:["Spa","Corte de pelo","Corte de uñas","Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Limpieza dental","Corte de uñas"],consequents:["Corte de pelo"]},
{antecedents:["Corte de pelo","Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Tratamiento de sarna","Corte de uñas","Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Tratamiento de sarna"],consequents:["Limpieza dental"]},
{antecedents:["Limpieza dental","Spa"],consequents:["Corte de pelo"]},
{antecedents:["Limpieza dental","Spa","Corte de uñas","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Tratamiento de sarna","Corte de uñas"],consequents:["Corte de pelo"]},
{antecedents:["Tratamiento de sarna","Corte de uñas"],consequents:["Limpieza dental"]},
{antecedents:["Limpieza dental"],consequents:["Corte de pelo"]},
{antecedents:["Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Tratamiento de sarna","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Spa","Tratamiento de sarna","Baño para perros","Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Tratamiento de sarna","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Spa","Tratamiento de sarna","Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Corte de uñas","Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Tratamiento de sarna","Corte de uñas","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Corte de uñas"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Tratamiento de sarna","Corte de uñas","Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Limpieza dental","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Limpieza dental","Spa","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Spa","Corte de pelo","Corte de uñas"],consequents:["Limpieza dental"],"antecedent support":0.4285714286,"consequent support":0.8319327731,"support":0.3613445378,"confidence":0.8431372549,"lift":1.0134680135,"leverage":0.0048019208,"conviction":1.0714285714,"zhangs_metric":0.023255814},
{antecedents:["Limpieza dental","Corte de uñas","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Tratamiento de sarna","Corte de uñas","Baño para perros"],consequents:["Corte de pelo"]},
{antecedents:["Corte de uñas"],consequents:["Corte de pelo"]},
{antecedents:["Spa","Corte de uñas"],consequents:["Corte de pelo"]},
{antecedents:["Spa"],consequents:["Corte de pelo"]},
{antecedents:["Spa","Corte de pelo"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Corte de pelo","Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Tratamiento de sarna"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Tratamiento de sarna","Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Corte de uñas","Baño para perros"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Corte de uñas"],consequents:["Limpieza dental"]},
{antecedents:["Spa"],consequents:["Limpieza dental"]},
{antecedents:["Spa","Tratamiento de sarna","Corte de uñas"],consequents:["Limpieza dental"]}

]

export default reglas;